config/routes.rb
Idealist::Application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :ideas do
    member { post :vote }
  end
  
  root to: 'ideas#index'

end

app/models/idea.rb
# encoding: utf-8

class Idea < ActiveRecord::Base
  attr_accessible :title, :description, :address, :latitude, :longitude, :image, :remote_image_url
  geocoded_by :full_address
  after_validation :geocode, if: :address_changed?
  mount_uploader :image, ImageUploader
  
  belongs_to :user
  has_reputation :votes, source: :user, aggregated_by: :sum
  
  validates_presence_of :title
  validates_presence_of :description
  validates :image,
    presence: true,
    file_size: {
      maximum: 1.megabyte.to_i
    }
  
  def image_name
    File.basename(image.path || image.filename) if image
  end
  
  
  private
  
  def full_address
    self[:address].to_s + ", Wrocław, Poland"
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_filter :require_authentication, only: [:new, :create, :vote]
  before_filter :require_admin, only: [:edit, :update, :destroy]
  
  def index
    @ideas = Idea.find_with_reputation(:votes, :all, order: "votes DESC")
  end

  def show
    @idea = Idea.find(params[:id])
  end

  def new
    @idea = Idea.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @idea = current_user.ideas.build(params[:idea])
    
    if @idea.save
      respond_to do |format|
        format.html { redirect_to action: "index", :notice => "Pomysł został zapisany." }
        format.js
      end
    else
      respond_to do |format|
        format.html { render :action => 'new' }
        format.js { render template: 'ideas/new.js.erb' }
      end
    end
  end

  def edit
    @idea = Idea.find(params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    @idea = Idea.find(params[:id])
    if @idea.update_attributes(params[:idea])
      respond_to do |format|
        format.html { redirect_to action: "index", :notice => "Pomysł został zapisany." }
        format.js
      end
    else
      respond_to do |format|
        format.html { render :action => 'edit' }
        format.js { render template: 'ideas/edit.js.erb' }
      end
    end
  end

  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy
    redirect_to ideas_url, :notice => "Pomysł został usunięty."
  end
  
  def vote
    value = params[:type] == "up" ? 1 : -1
    @idea = Idea.find(params[:id])
    @idea.add_or_update_evaluation(:votes, value, current_user)
    redirect_to :back, notice: "Dziękujemy za Twój głos."
  end
  
  private

  def js_compatible_redirect_to(url)
    respond_to do |format|
      format.html do 
        redirect_to url 
      end
      
      format.js do 
        render js: "window.location = #{url.to_json};"
      end
    end
  end
    
  def require_authentication
    js_compatible_redirect_to(new_user_session_url) unless user_signed_in?
  end

  def require_admin
    js_compatible_redirect_to(new_user_session_url) unless current_user.try(:admin)
  end
end

app/helpers/ideas_helper.rb
module IdeasHelper
  def human_address(idea)
    if idea.address.blank?
      "Wrocław"
    else
      @idea.address 
    end
  end
  
  def map_url(idea, options = {})
    width = options[:width] || 400
    height = options[:height] || 400
    zoom = idea.address.blank? ? 13 : 16
    "http://maps.google.com/maps/api/staticmap?size=#{width}x#{height}&sensor=false&zoom=#{zoom}&markers=#{idea.latitude}%2C#{idea.longitude}"
  end
end

app/views/ideas/_edit_links.html.haml
.edit_links
  - if current_user.try(:admin?) || idea.user == current_user
    = link_to "Edytuj", edit_idea_path(idea), remote: true
    |
    = link_to "Usuń", idea, :confirm => 'Czy na pewno usunąć?', :method => :delete 

app/views/ideas/_form.html.haml
= form_for @idea, html: { class: "form-horizontal" }, remote: true do |f|
  .control-group
    .controls
      = f.error_messages

  .control-group
    = f.label :title, class: 'control-label required'
    .controls
      = f.text_field :title, class: "span6 required"

  .control-group
    = f.label :description, class: 'control-label required'
    .controls
      = f.text_area :description, class: "span6", rows: 5

  .control-group
    = f.label :image, "Zdjęcie", class: 'control-label required'
    .controls
      = f.file_field :image
      = f.label :remote_image_url, "lub wpisz adres Internetowy"
      = f.text_field :remote_image_url

  .control-group
    = f.label :address, class: 'control-label'
    .controls
      = f.text_field :address, class: "span6"
  .control-group
    .controls
      = f.submit class: 'btn btn-primary', disable_with: "Zapisuję..."
      &nbsp;
      = link_to_function 'Zamknij', 'var form = $(this).parents("form"); form.prev().show(); form.remove();', class: 'cancel_button'

app/views/ideas/_idea.html.haml
%div{class: dom_id(idea)}
  .well.idea
    .media
      %a.pull-left{href: idea_path(idea), style: "max-width: 200px;"}
        .thumbnail
          / = image_tag idea.image_url(:thumb).to_s
          = image_tag "http://maps.google.com/maps/api/staticmap?size=600x600&sensor=false&zoom=16&markers=#{idea.latitude}%2C#{idea.longitude}"
  


      .media-body
        %h4.media-heading= idea.title
        %p
          - max_len = 300
          = truncate(idea.description, length: max_len, omission: "")
          - if idea.description.length > max_len
            = link_to "Więcej...", idea
        = render "vote", idea: idea
    
    = render "edit_links", idea: idea

app/views/ideas/_vote.html.haml
Głosów:
= idea.reputation_for(:votes).to_i
- if current_user && current_user != idea.user
  &nbsp;
  = link_to "Za", vote_idea_path(idea, type: "up"), method: "post"
  |
  = link_to "Przeciw", vote_idea_path(idea, type: "down"), method: "post"

app/views/ideas/create.js.erb
$('#new_idea').remove();
$('#new_link').show();
$('#ideas').prepend('<%= j render("idea", idea: @idea) %>');

app/views/ideas/edit.html.haml
- title "Pomysł"

= render 'form'

app/views/ideas/edit.js.erb
$(".<%= dom_id(@idea) %>").find("#edit_idea").remove();
$(".<%= dom_id(@idea) %>").find('.edit_links').hide().after('<%= j render("form", idea: @idea) %>');

app/views/ideas/index.html.haml
- title "Pomysły"

:css
  .idea {
    margin-top: 20px;
    margin-bottom: 0px;
  }
  
  #new_idea {
    background-color: #FCF8E3;
  }
  
  #new_idea {
    padding-bottom: 8px;
  }
  
  .cancel_button {
    display: inline-block;
  }

%p= link_to "Dodaj pomysł", new_idea_path, class: "btn btn-primary btn-large", id: "new_link", remote: true

#ideas
  = render @ideas

app/views/ideas/new.html.haml
- title "Nowy Pomysł"

= render 'form'

app/views/ideas/new.js.erb
$("#new_idea").remove();
$('#new_link').hide().after('<%= j render("form", remote_form: true) %>');

app/views/ideas/show.html.haml
- title @idea.title



.well
  .media
    %a.pull-left{href: "#", style: "max-width: 200px;", "data-toggle" => "lightbox", href: "#fullsizeImage"}
      .thumbnail
        = image_tag @idea.image_url(:thumb).to_s
    
    .media-body
      %h4.media-heading Jaki pomysł?
      %p= @idea.description
      %p= render "vote", idea: @idea


  .media
    %a.pull-right{href: "#", style: "max-width: 200px", "data-toggle" => "lightbox", href: "#fullsizeMap"}
      .thumbnail
        = image_tag map_url(@idea, width: 200, height: 200)     

  .media-body
    %h4.media-heading Gdzie?
    = human_address(@idea)


#fullsizeImage.lightbox.hide.fade{tabindex: "-1", role: "dialog", "aria-hidden" => true}
  .lightbox-content
    = image_tag @idea.image_url.to_s
    .lightbox-caption
      %p= @idea.title
      
#fullsizeMap.lightbox.hide.fade{tabindex: "-1", role: "dialog", "aria-hidden" => true}
  .lightbox-content
    = image_tag map_url(@idea, width: 600, height: 400) 
    .lightbox-caption
      %p= human_address(@idea)
      

app/views/ideas/update.js.erb
$(".<%= dom_id(@idea) %>").replaceWith('<%= j render("idea", idea: @idea) %>');