config/routes.rb
Idealist::Application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :ideas do
    member { post :vote }
  end
  
  root to: 'ideas#index'

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/application.html.haml
!!!
%html

  %head
    %title
      = yield(:title)
      \ - 
      WROKREACJE.PL
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}/
    = stylesheet_link_tag "application"
    = javascript_include_tag :application
    = csrf_meta_tag
    = yield(:head)

  %body
    %header
      .navbar.navbar-fixed-top.navbar-inverse
        .navbar-inner
          .container
            %a.btn.btn-navbar{"data-toggle" => "collapse", "data-target" => ".nav-collapse"}
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            %a.brand{href: root_path} WROKREACJE.PL
            .nav-collapse
              %ul.nav
                %li
                  = link_to "Pomysły", ideas_path
                - if user_signed_in?
                  %li= link_to current_user.email, edit_user_registration_path 
                  %li= link_to "Wyloguj się", destroy_user_session_path, method: :delete
                -else
                  %li= link_to "Utwórz konto", new_user_registration_path
                  %li= link_to "Zaloguj się", new_user_session_path
                  %li
                    %a{href: user_omniauth_authorize_path(:facebook)}
                      = image_tag "fb_login_button_m.png"
    #container#content
      .row
        .span10.offset2#content_column
          - flash.each do |name, msg|
            = content_tag :div, msg, :id => "flash_#{name}", :class => name

          - if show_title?
            / %h1#page_title= yield(:title)
            %ul.breadcrumb
              %li
                - unless current_page?(root_url)
                  %a{href: root_path}
                    Strona Główna
                  %span.divider
                %li.active
                  %h1#page_title= yield(:title)

          = yield